<a href="https://colab.research.google.com/github/softstat/AI_machine_learning/blob/main/practice/week2/1_pandas_data_structures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import os
import sys
os.listdir()

['.config', 'drive', 'sample_data']

In [4]:
cd drive

/content/drive


In [5]:
os.listdir()

['MyDrive', '.shortcut-targets-by-id', '.file-revisions-by-id', '.Trash-0']

In [6]:
cd MyDrive

/content/drive/MyDrive


In [8]:
cd Hands-On-Data-Analysis-with-Pandas-2nd-edition/

/content/drive/MyDrive/Hands-On-Data-Analysis-with-Pandas-2nd-edition


In [9]:
cd ch_02

/content/drive/MyDrive/Hands-On-Data-Analysis-with-Pandas-2nd-edition/ch_02


In [16]:
import numpy as np

data = np.genfromtxt(
    'data/example_data.csv',dtype=None,delimiter=';',
    names=True,encoding='UTF'
)
data

array([('2018-10-13 11:10:23.560', '262km NW of Ozernovskiy, Russia', 'mww', 6.7, 'green', 1),
       ('2018-10-13 04:34:15.580', '25km E of Bitung, Indonesia', 'mww', 5.2, 'green', 0),
       ('2018-10-13 00:13:46.220', '42km WNW of Sola, Vanuatu', 'mww', 5.7, 'green', 0),
       ('2018-10-12 21:09:49.240', '13km E of Nueva Concepcion, Guatemala', 'mww', 5.7, 'green', 0),
       ('2018-10-12 02:52:03.620', '128km SE of Kimbe, Papua New Guinea', 'mww', 5.6, 'green', 1)],
      dtype=[('time', '<U23'), ('place', '<U37'), ('magType', '<U3'), ('mag', '<f8'), ('alert', '<U5'), ('tsunami', '<i8')])

we can find the dimensions with **shape** attribute:

In [17]:
data.dtype

dtype([('time', '<U23'), ('place', '<U37'), ('magType', '<U3'), ('mag', '<f8'), ('alert', '<U5'), ('tsunami', '<i8')])

list 연습

In [18]:
[i for i in range(3)]

[0, 1, 2]

In [19]:
[i*2 for i in range(3)]

[0, 2, 4]

In [20]:
[row[3] for row in data]

[6.7, 5.2, 5.7, 5.7, 5.6]

In [22]:
max([row[3] for row in data])

6.7

time 계산

In [23]:
%%timeit
max([row[3] for row in data])

19 µs ± 4.38 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Dictionary 알기

In [25]:
data.dtype.names

('time', 'place', 'magType', 'mag', 'alert', 'tsunami')

In [24]:
for i, col in enumerate(data.dtype.names):
    print(i,col)

0 time
1 place
2 magType
3 mag
4 alert
5 tsunami


In [26]:
[i for i,col in enumerate(data.dtype.names)]

[0, 1, 2, 3, 4, 5]

In [29]:
array_dict = {
    col : np.array([row[i] for row in data])
    for i,col in enumerate(data.dtype.names)}
array_dict

{'time': array(['2018-10-13 11:10:23.560', '2018-10-13 04:34:15.580',
        '2018-10-13 00:13:46.220', '2018-10-12 21:09:49.240',
        '2018-10-12 02:52:03.620'], dtype='<U23'),
 'place': array(['262km NW of Ozernovskiy, Russia', '25km E of Bitung, Indonesia',
        '42km WNW of Sola, Vanuatu',
        '13km E of Nueva Concepcion, Guatemala',
        '128km SE of Kimbe, Papua New Guinea'], dtype='<U37'),
 'magType': array(['mww', 'mww', 'mww', 'mww', 'mww'], dtype='<U3'),
 'mag': array([6.7, 5.2, 5.7, 5.7, 5.6]),
 'alert': array(['green', 'green', 'green', 'green', 'green'], dtype='<U5'),
 'tsunami': array([1, 0, 0, 0, 1])}

In [46]:
[row[0] for row in data]

['2018-10-13 11:10:23.560',
 '2018-10-13 04:34:15.580',
 '2018-10-13 00:13:46.220',
 '2018-10-12 21:09:49.240',
 '2018-10-12 02:52:03.620']

In [47]:
array_dict['mag']

array([6.7, 5.2, 5.7, 5.7, 5.6])

In [48]:
%%timeit
array_dict['mag'].max()

1.94 µs ± 498 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [49]:
for key,value in array_dict.items():
    print(key,value) ## key랑 value가 뭐지?

time ['2018-10-13 11:10:23.560' '2018-10-13 04:34:15.580'
 '2018-10-13 00:13:46.220' '2018-10-12 21:09:49.240'
 '2018-10-12 02:52:03.620']
place ['262km NW of Ozernovskiy, Russia' '25km E of Bitung, Indonesia'
 '42km WNW of Sola, Vanuatu' '13km E of Nueva Concepcion, Guatemala'
 '128km SE of Kimbe, Papua New Guinea']
magType ['mww' 'mww' 'mww' 'mww' 'mww']
mag [6.7 5.2 5.7 5.7 5.6]
alert ['green' 'green' 'green' 'green' 'green']
tsunami [1 0 0 0 1]


In [50]:
np.array([value[array_dict['mag'].argmax()]
          for key,value in array_dict.items()])

array(['2018-10-13 11:10:23.560', '262km NW of Ozernovskiy, Russia',
       'mww', '6.7', 'green', '1'], dtype='<U32')

## Series

In [51]:
import pandas as pd
place= pd.Series(array_dict['place'],name='place')
place

0          262km NW of Ozernovskiy, Russia
1              25km E of Bitung, Indonesia
2                42km WNW of Sola, Vanuatu
3    13km E of Nueva Concepcion, Guatemala
4      128km SE of Kimbe, Papua New Guinea
Name: place, dtype: object

In [61]:
place.values

array(['262km NW of Ozernovskiy, Russia', '25km E of Bitung, Indonesia',
       '42km WNW of Sola, Vanuatu',
       '13km E of Nueva Concepcion, Guatemala',
       '128km SE of Kimbe, Papua New Guinea'], dtype=object)

In [62]:
place.name

'place'

In [63]:
place.shape

(5,)

## Index

In [52]:
place_index = place.index
place_index

RangeIndex(start=0, stop=5, step=1)

In [53]:
place_index.values

array([0, 1, 2, 3, 4])

In [64]:
place_index.dtype

dtype('int64')

we can check if the values are unique

In [65]:
place_index.is_unique

True

With Nympy we can perform arithmetic operations element-wise between arrays

In [66]:
np.array([-1,0,1]) + np.array([1,1,1])

array([0, 1, 2])

### matching index values

In [56]:
numbers = np.linspace(0,10,num=5) # [0,2.5,5.0,7.5,10]
x = pd.Series(numbers) # index [0,1,2,3,4]
y = pd.Series(numbers,index=pd.Index([1,2,3,4,5])) # index [1,2,3,4,5]
x+y

0     NaN
1     2.5
2     7.5
3    12.5
4    17.5
5     NaN
dtype: float64

## DataFrame

In [57]:
df = pd.DataFrame(array_dict)
df

time                                  place magType  \
0  2018-10-13 11:10:23.560        262km NW of Ozernovskiy, Russia     mww   
1  2018-10-13 04:34:15.580            25km E of Bitung, Indonesia     mww   
2  2018-10-13 00:13:46.220              42km WNW of Sola, Vanuatu     mww   
3  2018-10-12 21:09:49.240  13km E of Nueva Concepcion, Guatemala     mww   
4  2018-10-12 02:52:03.620    128km SE of Kimbe, Papua New Guinea     mww   

   mag  alert  tsunami  
0  6.7  green        1  
1  5.2  green        0  
2  5.7  green        0  
3  5.7  green        0  
4  5.6  green        1

In [59]:
df.columns

Index(['time', 'place', 'magType', 'mag', 'alert', 'tsunami'], dtype='object')

In [67]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [68]:
df.shape

(5, 6)

In [69]:
df + df

time  \
0  2018-10-13 11:10:23.5602018-10-13 11:10:23.560   
1  2018-10-13 04:34:15.5802018-10-13 04:34:15.580   
2  2018-10-13 00:13:46.2202018-10-13 00:13:46.220   
3  2018-10-12 21:09:49.2402018-10-12 21:09:49.240   
4  2018-10-12 02:52:03.6202018-10-12 02:52:03.620   

                                               place magType   mag  \
0  262km NW of Ozernovskiy, Russia262km NW of Oze...  mwwmww  13.4   
1  25km E of Bitung, Indonesia25km E of Bitung, I...  mwwmww  10.4   
2  42km WNW of Sola, Vanuatu42km WNW of Sola, Van...  mwwmww  11.4   
3  13km E of Nueva Concepcion, Guatemala13km E of...  mwwmww  11.4   
4  128km SE of Kimbe, Papua New Guinea128km SE of...  mwwmww  11.2   

        alert  tsunami  
0  greengreen        2  
1  greengreen        0  
2  greengreen        0  
3  greengreen        0  
4  greengreen        2